server:
port:8080

spring:
datasource:
  url:jdbc:mysql://localhost:3306/realm?characterEncoding=Utf-8
  username:root
  password:base123
  driver-class-name:com.mysql.jdbc.Driver
redis:
 host:localhost
 port:6379
 timeout:0
 password:lanxin

 mybatis:
   mapper-locations:classpath:mapper/*.xml
   type-aliases-package:com.lanxin
   configuration:
    log-impl:org.apache.ibatis.logging.stdout.StdoutImpl
